'''
    Simple shared enum for pool statusing
'''


class PoolStatus:
    '''
        Namespacing class
        Not quite an ENUM
    '''
    UNSTARTED = 'UNSTARTED'
    STARTING = 'STARTING'
    STARTED = 'STARTED'
    STARTING_WORKERS = 'STARTING_WORKERS'
    STARTED_WORKERS= 'STARTED_WORKERS'
    IDLE = 'IDLE'
    SYNCHRONISING = 'SYNCHRONISING'
    SYNCHRONISED = 'SYNCHRONISED'
    PREPROCESSING = 'PREPROCESSING'
    PREPROCESSING = 'PREPROCESSED'
    EXECUTING = 'EXECUTING'
    FINISHED = 'FINISHED'
