'''
    Generic plugin manager class

    This only exists to avoid duplication between the
        execution and architecture plugin managers
'''
import os
import sys
import types
import importlib

from collections import OrderedDict

from .. import config


#   Format string as part of a not implemented exception
PLUGIN_NOT_IMPL_ERROR = "Target {} in module {} does not return a string when calling static or class method get_name()"

class PluginManager:
    '''
       Architecture Plugin manager
    '''
    _config_file_name: str | None = None
    # Used for unique namespaces for dynamically loaded plugins
    GLB_COUNTER = 0


    def __init__(
            self,
            *,
            module_tag: str,
            modules: list,
            config_path=None):
        '''
            Generic plugin manager
            Used to manage loading resources from disparate modules
            :: module_tag : str :: Default tag for module level names of resources
        '''
        # Tag for variable name in modules to extract
        self._module_tag = module_tag

        # All modules loaded to extract options
        self._modules = set(modules)
        self._file_paths = OrderedDict()

        # Hashmap of all loaded options
        # Keys are generated by getname
        self._options: dict = {}

        # Currently selection option
        self._current_option: None = None

        # Dynamically definable parameter field
        self._parameters = {}

        # Load modules
        if len(modules) > 0:
            self.load_options_from_modules(*modules)

        if config_path is not None:
            self.load_options_from_config(config_path)

    def __len__(self):
        return len(self._options)

    def __getitem__(self, key):
        '''
            Getter based on keys
        '''
        return self._options.get(key, None)

    def __iter__(self):
        return self._options.__iter__()

    def get_module_names(self) -> list[str]:
        '''
            Get string names of all loaded modules
            Useful for synchronising
        '''
        return [
            module.__name__
            for module in self._modules
        ]

    def get_non_filepath_module_names(self) -> list[str]:
        '''
            Get string names for all loaded modules
            Without modules that were loaded from paths.
        '''
        return [
            module.__name__
            for module in self._modules
            if module not in self._file_paths
        ]

    def get_loaded_filepaths(self) -> list[str]:
        '''
            Gets any modules loaded by file path
            Useful for synchronising
        '''
        return list(self._file_paths.values())

    def get_synchronisation_strings(self):
        '''
            Shorthand for getting string
             representations of loaded objects
        '''
        return (
            self.get_non_filepath_module_names()
            + self.get_loaded_filepaths()
        )

    @classmethod
    def default_loader(cls) -> 'PluginManager':
        '''
            Wrapper to load from a default configuration
        '''
        return default_loader(
            cls._config_file_name,
            cls
        )

    def load_config(self, filepath: str):
        '''
            Short name wrapper
        '''
        return self.load_options_from_config(filepath)

    def load_options_from_config(self, filepath: str):
        '''
            Loads from a config file superclass
        '''
        options = self._load_options_from_config(filepath)

        if options is None:
            raise FileNotFoundError

        self._options |= options

    def load_options_from_modules(self, *modules):
        '''
            In place wrapper that updates options in place
        '''
        self._options |= self._load_options_from_modules(
            *modules
        )

    def _load_options_from_modules(self, *modules) -> dict:
        '''
            Loads constructors from modules
        '''

        if len(modules) == 0:
            modules = self._modules

        loaded_options = {}
        for module in modules:
            plugin_targets = getattr(
                module,
                self._module_tag,
                None
            )

            # Module has no targets exposed
            if plugin_targets is None:
                print(f"Module {module} does not contain any valid plugin targets")
                print(f'To expose a target at the module level, please set an iterable "{self._module_tag}" variable in the module\'s main namespace (e.g. __init__.py)')
                continue

            for target in plugin_targets:
                try:
                    key = target.get_name()
                    if not isinstance(key, str):
                        raise NotImplementedError(
    PLUGIN_NOT_IMPL_ERROR.format(target, module)
                        )

                    loaded_options[key] = target
                    self._modules.add(module)
                except AttributeError:
                    print(f"Object {target} in module {module} does not implement the required plugin interface")

        return loaded_options

    def _load_options_from_config(self, filepath: str) -> dict | type[FileNotFoundError]:
        '''
            Wrapper for loading from a config file
            Returns modules extracted from the config file
        '''
        try:
            modules = self._load_modules_from_config(
                filepath
            )
            module_objects = self._load_options_from_modules(
                *modules
            )
            return module_objects
        except FileNotFoundError as err:
            print(str(err))
            raise FileNotFoundError() from err

    @staticmethod
    def _load_modules_from_config(filepath) -> list[types.ModuleType]:
        modules = []
        with open(filepath, mode='r', encoding='ascii') as config_file:
            for entry in config_file:
                entry = entry.strip('\n')
                module = None
                try:
                    module = PluginManager._load_module_from_module_string(entry)
                except Exception as _e:
                    print(f"Failed to load {entry}: {_e}")
                if module is None:
                    try:
                        module = PluginManager._load_module_from_file_path(entry)
                    except Exception as _e:
                        print(f"Failed to load {entry}: {_e}")

                if module is None:
                    print(f"Entry {entry} could not be processed")
                else:
                    modules.append(module)
        return modules

    @staticmethod
    def _load_module_from_file_path(filepath: str) -> types.ModuleType:
        '''
           Loads a python module from file
        '''
        # Load counter for unique namespacing
        plugin_name = f'dynamically_loaded_module_{PluginManager.GLB_COUNTER}'
        PluginManager.GLB_COUNTER += 1

        spec = importlib.util.spec_from_file_location(plugin_name, filepath) # ty: ignore
        plugin_obj = importlib.util.module_from_spec(spec) # ty: ignore

        # NOTE: There should be better way instead of relying on sys here
        sys.modules[plugin_name] = plugin_obj
        spec.loader.exec_module(plugin_obj)

        return plugin_obj

    def load_modules_from_strings(self, *args):
        '''
            Loads modules from strings
            Defers to either a python module load or a path
        '''
        for entry in args:
            try:
                module = PluginManager._load_module_from_module_string(
                   entry
                )
                self._modules.add(module)
                continue
            except Exception as e:
                print(str(e))

            # Attempt to treat it as a file path
            try:
                # O(n) call, but should be small
                # Needed as file paths need to be ordered
                module = PluginManager._load_module_from_file_path(
                    entry
                )
                if module not in self._file_paths:
                    self._modules.add(module)
                    self._file_paths[module] = entry
            except Exception as e:
                print(str(e))

        # Force reload
        self.load_options_from_modules()

    @staticmethod
    def _load_module_from_module_string(module_name: str) -> types.ModuleType:
        '''
           Loads a python module from module space
        '''
        module = importlib.import_module(module_name)
        return module

    def _set_current_option(self, key: str):
        '''
            Setter for the currently selected option
        '''

        option = self[key]
        if option is None:
            print(f"Unknown option {key}")
        else:
            self._current_option = option

    def get_parameters(self):
        '''
            Parameters getter
        '''
        return self._parameters


    def set_parameters(self, parameters):
        '''
            Parameters setter
        '''
        self._parameters = parameters



# NOTE: Moved it from config
# Using the default loader built-in now
def default_loader(
        config_file_name: str | None,
        constructor: type['PluginManager'],
        ) -> type['PluginManager']:
    '''
        default_loader

        Generic loader for configuration files to
        the plugin manager.
        Checks each location specified in the
        configuration file, attempts to load using
        the provided constructor and returns the
        created plugin manager
    '''

    for loc in config.configuration_locations:
        # TODO: Consider composing multiple configs
        # rather than just using the first
        config_path = os.path.expanduser(f'{loc}/{config_file_name}')

        # Check if file exists
        # File error handling is managed in the
        # constructor
        if os.path.isfile(config_path):
            return constructor(
                config_path=config_path
            )
        print("Unable to load configuration" + config_path)
    # No configuration files found
    return constructor()


def _load_default_config(conf_name, plugin_obj):
    for loc in config.configuration_locations:
        config_path = os.path.expanduser(f'{loc}/{conf_name}')

        # Check if file exists
        # File error handling is managed in the
        # constructor
        if os.path.isfile(config_path):
            try:
                plugin_obj.load_options_from_config(config_path)
            except Exception as e:
                print(str(e))
