'''
    Generic plugin manager class

    This only exists to avoid duplication between the
        execution and architecture plugin managers
'''
import sys
import types
import importlib

from .config_loader import default_loader

# Used for unique namespaces for dynamically loaded plugins
GLB_COUNTER = 0

'''
   Format string as part of a not implemented exception 
'''
PLUGIN_NOT_IMPL_ERROR = "Target {} in module {} does not return a string when calling static or class method get_name()"


class PluginManager:
    '''
       Architecture Plugin manager
    '''
    _config_file_name = None

    def __init__(
            self,
            *,
            module_tag: str,
            modules: list,
            config_path=None):
        '''
            Generic plugin manager
            Used to manage loading resources from disparate modules
            :: module_tag : str :: Default tag for module level names of resources
        '''
        # Tag for variable name in modules to extract
        self._module_tag = module_tag

        # All modules loaded to extract options
        self._modules = modules

        # Hashmap of all loaded options
        # Keys are generated by getname
        self._options = {}

        # Currently selection option
        self._current_option = None

        # Load modules
        if len(modules) > 0:
            self.load_options_from_modules(*modules)

        if config_path is not None:
            self.load_options_from_config(config_path)

    def __getitem__(self, key):
        '''
            Getter based on keys
        '''
        return self._options.get(key, None)

    @classmethod
    def default_loader(cls) -> 'cls':
        '''
            Wrapper to load from a default configuration
        '''
        return default_loader(
            cls._config_file_name,
            cls
        )

    @classmethod
    def load_config_or_default(cls, filepath: str):
        '''
           Loads the configuration or will attempt to
           load the defaults 
        '''
        plugin = cls.default_loader()
        plugin.load_config(filepath)
        

    def load_config(self, filepath: str):
        '''
            Short name wrapper
        '''
        return self.load_options_from_config(filepath)

    def load_options_from_config(self, filepath: str):
        '''
            Loads from a config file
            superclass
        '''
        options = self._load_options_from_config(filepath)
        if options is FileNotFoundError:
            return FileNotFoundError

        self._options |= options
        return None

    def load_options_from_modules(self, *modules):
        '''
            In place wrapper that updates options in place
        '''
        self._options |= self._load_options_from_modules(*modules)

    def _load_options_from_modules(self, *modules) -> dict:
        '''
            Loads constructors from modules
        '''

        if len(modules) == 0:
            modules = self._modules

        loaded_options = {}
        for module in modules:
            plugin_targets = getattr(
                module,
                self._module_tag,
                None
            )

            # Module has no targets exposed
            if plugin_targets is None:
                print(f"Module {module} does not contain any valid plugin targets")
                print(f'To expose a target at the module level, please set an iterable "{self._module_tag}" variable in the module\'s main namespace (e.g. __init__.py)')
                continue

            for target in plugin_targets:
                try:
                    key = target.get_name()
                    if not isinstance(key, str):
                        raise NotImplementedError(PLUGIN_NOT_IMPL_ERROR.format(target, module))
                    loaded_options[key] = target
                except AttributeError:
                    print(f"Object {target} in module {module} does not implement the required plugin interface")

        return loaded_options

    def _load_options_from_config(self, filepath: str) -> dict:
        '''
            Wrapper for loading from a config file
            Returns modules extracted from the config file
        '''
        try:
            modules = self._load_modules_from_config(
                filepath
            )
            module_objects = self._load_options_from_modules(
                *modules
            )
            return module_objects
        except FileNotFoundError:
            return FileNotFoundError

    @staticmethod
    def _load_modules_from_config(filepath) -> list[types.ModuleType]:

        modules = []
        with open(filepath, mode='r', encoding='ascii') as config:
            for entry in config:
                entry = entry.strip('\n')
                module = None
                try:
                    module = PluginManager._load_module_from_module_string(entry)
                except Exception as _e:
                    pass

                try:
                    module = PluginManager._load_module_from_file_path(entry)
                except Exception as _e:
                    pass

                if module is None:
                    print(f"Entry {entry} could not be processed")
                else:
                    modules.append(module)
        return modules

    @staticmethod
    def _load_module_from_file_path(filepath: str) -> types.ModuleType:
        '''
           Loads a python module from file
        '''
        # Load counter for unique namespacing
        global GLB_COUNTER
        plugin_name = f'dynamically_loaded_module_{GLB_COUNTER}'
        GLB_COUNTER += 1

        spec = importlib.util.spec_from_file_location(plugin_name, filepath)
        plugin_obj = importlib.util.module_from_spec(spec)

        # NOTE: There should be better way instead of relying on sys here
        sys.modules[plugin_name] = plugin_obj
        spec.loader.exec_module(plugin_obj)

        return plugin_obj

    @staticmethod
    def _load_module_from_module_string(module_name: str) -> types.ModuleType:
        '''
           Loads a python module from module space
        '''
        module = importlib.import_module(module_name)
        return module

    def _set_current_option(self, key: str):
        '''
            Setter for the currently selected option
        '''
        option = self[key]
        if option is None:
            print(f"Unknown option {key}")
        else:
            self._current_option = option
